# Goal
string parent_frame_id
string child_frame_id
geometry_msgs/Transform transform

---
# Result
bool success
string message
geometry_msgs/TransformStamped door_handle
geometry_msgs/TransformStamped door_hinge

---
# Feedback
string status
