door_pose_estimation_action_server:
  ros__parameters:
    action_name: estimate_door_poses
    broadcast_result_tf: true

    # These select which generated frames populate the action result fields.
    door_handle_frame_id: door_handle
    handle_interaction_frame_id: handle_interaction
    door_hinge_frame_id: door_hinge

    generated_frame_ids:
      - door_handle
      - handle_interaction
      - door_hinge

    # Pose formats:
    # - 6 values: [x, y, z, thz, thy, thx]
    # - 7 values: [x, y, z, qw, qx, qy, qz]
    generated_frames.door_handle.pose: [0.375, 0.1, 0.05, 0.0, 0.0, 0.0]
    generated_frames.handle_interaction.pose: [0.3, 0.0, 0.05, 0.0, 3.14159, 0.0]
    generated_frames.door_hinge.pose: [-0.435, 1.055, 0.0, 0.0, 0.0, 1.5708]
